# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RoomManage', '0002_auto_20170427_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='RoomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemManage.Item', to_field='name')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomManage.Room')),
            ],
        ),
    ]
