# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomitem',
            old_name='item',
            new_name='item_name',
        ),
    ]
