# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemManage', '0002_auto_20170427_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitem',
            name='amount',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
