# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemManage', '0003_auto_20170429_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
