# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('cost', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('reserve_date', models.DateTimeField(null=True)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=30)),
                ('custom_gender', models.CharField(max_length=5)),
                ('customs_id', models.IntegerField(unique=True)),
                ('phone_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateTimeField()),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomManage.Customs')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('room_type', models.CharField(max_length=15)),
                ('room_price', models.IntegerField()),
                ('room_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomManage.Room'),
        ),
        migrations.AddField(
            model_name='customs',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomManage.Room'),
        ),
        migrations.AddField(
            model_name='bills',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomManage.Customs'),
        ),
        migrations.AddField(
            model_name='bills',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomManage.Room'),
        ),
    ]
