# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customs',
            name='customs_id',
        ),
        migrations.RemoveField(
            model_name='customs',
            name='room',
        ),
        migrations.AddField(
            model_name='customs',
            name='custom_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='reserve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(default='uncheck', max_length=15),
        ),
    ]
