# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManage', '0003_auto_20170427_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='cost_item',
        ),
        migrations.AddField(
            model_name='cost_item',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RoomManage.Bills'),
            preserve_default=False,
        ),
    ]
