# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManage', '0005_auto_20170516_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='未完成', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(default='未入住', max_length=15),
        ),
    ]
