# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0003_emergency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'permissions': (('create_emergency', 'can create a emergency'),)},
        ),
    ]
