# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitManage', '0002_auto_20170516_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='name',
            field=models.CharField(default='name', max_length=128),
        ),
    ]
